version: '3'
services:
  bcb:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
    container_name: banco-central
    ports:
      - 8082:8082

  erp-itau:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
    container_name: itau
    ports:
      - 9091:9091

  db:
    image: mysql
    container_name: mysql-pix
    environment:
      MYSQL_ROOT_PASSWORD: pix
    ports:
      - "3306:3306"
    volumes:
      - pix_volume:/var/lib/mysql

volumes:
  pix_volume: