micronaut:
  application:
    name: keyManager
    server:
        access-logger:
          enabled: true # Enables the access logger
          logger-name: my-access-logger # A logger name, optional, default is `HTTP_ACCESS_LOGGER`
          log-format: common # A log format, optional, default is Common Log Format

datasources:
  default:
    url: jdbc:mysql://localhost:3306/pix?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: pix
    dialect: org.hibernate.dialect.MySQLInnoDBDialect

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
